"use client";

import { useState } from "react";
import { VaultCard } from "@/components/VaultCard";
import { AlertPanel } from "@/components/AlertPanel";
import { MOCK_POSITIONS, MOCK_POSITIONS_REFRESH } from "@/lib/mock-data";
import { generateAlerts } from "@/lib/alert-engine";
import { VaultPosition } from "@/lib/types";

const MOCK_ADDRESS = "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045";

export default function Home() {
  const [positions, setPositions] = useState<VaultPosition[]>(MOCK_POSITIONS);
  const [refreshCount, setRefreshCount] = useState(0);
  const [refreshing, setRefreshing] = useState(false);

  const alerts = generateAlerts(positions);
  const criticalCount = alerts.filter((a) => a.severity === "critical").length;
  const warningCount = alerts.filter((a) => a.severity === "warning").length;

  function handleRefresh() {
    setRefreshing(true);
    setTimeout(() => {
      const next = refreshCount % 2 === 0 ? MOCK_POSITIONS_REFRESH : MOCK_POSITIONS;
      setPositions(next);
      setRefreshCount((c) => c + 1);
      setRefreshing(false);
    }, 900);
  }

  return (
    <main className="min-h-screen bg-slate-950 text-white">
      {/* Header */}
      <div className="border-b border-slate-800 bg-slate-900/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-7 w-7 rounded-full bg-gradient-to-br from-blue-500 to-cyan-400 flex items-center justify-center text-xs font-bold">
              L
            </div>
            <div>
              <h1 className="text-sm font-bold text-white">Lido Earn Monitor</h1>
              <p className="text-[11px] text-slate-500">Vault alert agent</p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <AlertSummaryBadge critical={criticalCount} warning={warningCount} />
            <button
              onClick={handleRefresh}
              disabled={refreshing}
              className="text-xs px-3 py-1.5 rounded-lg border border-slate-700 text-slate-300 hover:bg-slate-800 hover:border-slate-600 transition-all disabled:opacity-50"
            >
              {refreshing ? "Refreshing…" : "Refresh"}
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 space-y-8">
        {/* Wallet context */}
        <div className="flex items-center gap-2 text-xs text-slate-500">
          <span className="inline-block h-2 w-2 rounded-full bg-emerald-500" />
          <span>
            Monitoring{" "}
            <span className="font-mono text-slate-400">
              {MOCK_ADDRESS.slice(0, 6)}…{MOCK_ADDRESS.slice(-4)}
            </span>
            <span className="ml-2 text-slate-600">(demo — no wallet connected)</span>
          </span>
        </div>

        {/* Vault positions */}
        <section>
          <SectionHeader
            title="Your Positions"
            sub={`${positions.length} active vault${positions.length !== 1 ? "s" : ""}`}
          />
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {positions.map((pos) => (
              <VaultCard key={pos.vaultId} position={pos} />
            ))}
          </div>
        </section>

        {/* Alert feed */}
        <section>
          <SectionHeader
            title="Alerts"
            sub={
              alerts.length > 0
                ? `${alerts.length} active alert${alerts.length !== 1 ? "s" : ""}`
                : "No active alerts"
            }
          />
          <AlertPanel alerts={alerts} />
        </section>

        {/* Footer note */}
        <p className="text-center text-xs text-slate-700 pb-4">
          Vault state is seeded demo data. Alerts are generated by the local alert engine.
          Wire up Lido JS SDK for live reads.
        </p>
      </div>
    </main>
  );
}

function SectionHeader({ title, sub }: { title: string; sub: string }) {
  return (
    <div className="flex items-baseline justify-between mb-3">
      <h2 className="text-sm font-semibold text-white uppercase tracking-wide">{title}</h2>
      <span className="text-xs text-slate-500">{sub}</span>
    </div>
  );
}

function AlertSummaryBadge({
  critical,
  warning,
}: {
  critical: number;
  warning: number;
}) {
  if (critical === 0 && warning === 0) {
    return (
      <span className="text-xs text-emerald-500 flex items-center gap-1">
        <span className="h-1.5 w-1.5 rounded-full bg-emerald-500" />
        All clear
      </span>
    );
  }
  return (
    <div className="flex items-center gap-1.5">
      {critical > 0 && (
        <span className="text-[11px] px-2 py-0.5 rounded-full bg-red-900/60 border border-red-700 text-red-400 font-medium">
          {critical} critical
        </span>
      )}
      {warning > 0 && (
        <span className="text-[11px] px-2 py-0.5 rounded-full bg-amber-900/60 border border-amber-700 text-amber-400 font-medium">
          {warning} warning
        </span>
      )}
    </div>
  );
}
